services:
    PiouPiou\AgriGestionBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    PiouPiou\AgriGestionBundle\Controller\:
        resource: '../../Controller'
        calls:
            - [setContainer, ["@service_container"]]
        tags: ['controller.service_arguments']

    PiouPiou\AgriGestionBundle\EventListener\CreateUpdateAwareListener:
        arguments: [ "@security.untracked_token_storage" ]
        tags:
            - { name: doctrine.orm.entity_listener }
